<wsdl:definitions
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://hello"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata"
	xmlns:ns1="http://schemas.xmlsoap.org/soap/http" name="HelloIF"
	targetNamespace="http://hello">
	<wsdl:types>
		<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
			xmlns:tns="http://hello" attributeFormDefault="unqualified"
			elementFormDefault="unqualified" targetNamespace="http://hello">
			<xsd:import namespace="http://hello"
				schemaLocation="HelloIF-schema.xsd" />
		</xs:schema>
	</wsdl:types>
	<wsdl:message name="sayHelloHeader">
		<wsdl:part element="tns:sayHelloHeader" name="parameters">
		</wsdl:part>
		<wsdl:part element="tns:Header" name="Header">
		</wsdl:part>
	</wsdl:message>
	<wsdl:message name="sayHelloHeaderResponse">
		<wsdl:part element="tns:sayHelloHeader" name="result">
		</wsdl:part>
		<wsdl:part element="tns:Header" name="Header">
		</wsdl:part>
	</wsdl:message>
	<wsdl:message name="updateAddress">
		<wsdl:part element="tns:updateAddress" name="parameters">
		</wsdl:part>
	</wsdl:message>
	<wsdl:message name="updateAddressResponse">
		<wsdl:part element="tns:updateAddress" name="parameters">
		</wsdl:part>
	</wsdl:message>
	<wsdl:message name="isPalindrome">
		<wsdl:part name="parameters" element="tns:isPalindrome" />
	</wsdl:message>
	<wsdl:message name="isPalindromeResponse">
		<wsdl:part name="parameters"
			element="tns:isPalindromeResponse" />
	</wsdl:message>
	<wsdl:message name="PSBHeader">
		<wsdl:part element="tns:SSCAddressing" name="addr" />
	</wsdl:message>
	<wsdl:portType name="HelloIF">
		<wsdl:operation name="sayHelloHeader">
			<wsdl:input message="tns:sayHelloHeader"
				name="sayHelloHeader">
			</wsdl:input>
			<wsdl:output message="tns:sayHelloHeaderResponse"
				name="sayHelloHeaderResponse">
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="updateAddress">
			<wsdl:input message="tns:updateAddress"
				name="updateAddress">
			</wsdl:input>
			<wsdl:output message="tns:updateAddressResponse"
				name="updateAddressResponse">
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="isPalindrome">
			<wsdl:input wsam:Action="http://inv.aat.tools.dlg.nl/WordInvertor/isPalindromeRequest" message="tns:isPalindrome" /> <!-- wsam:Action="http://inv.aat.tools.dlg.nl/WordInvertor/isPalindromeRequest" -->
			<wsdl:output wsam:Action="http://inv.aat.tools.dlg.nl/WordInvertor/isPalindromeResponse" message="tns:isPalindromeResponse" /> <!-- wsam:Action="http://inv.aat.tools.dlg.nl/WordInvertor/isPalindromeResponse" -->
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="HelloIFSoapBinding" type="tns:HelloIF">
		<soap:binding style="document"
			transport="http://schemas.xmlsoap.org/soap/http" />
		<wsdl:operation name="sayHelloHeader">
			<soap:operation soapAction="" style="document" />
			<wsdl:input name="sayHelloHeader">
				<soap:header message="tns:sayHelloHeader" part="Header"
					use="literal">
				</soap:header>
				<soap:body parts="parameters" use="literal" />
			</wsdl:input>
			<wsdl:output name="sayHelloHeaderResponse">
				<soap:header message="tns:sayHelloHeaderResponse"
					part="Header" use="literal">
				</soap:header>
				<soap:body parts="result" use="literal" />
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="updateAddress">
			<soap:operation soapAction="" style="document" />
			<wsdl:input name="updateAddress">
				<soap:body use="literal" />
			</wsdl:input>
			<wsdl:output name="updateAddressResponse">
				<soap:body use="literal" />
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="isPalindrome">
			<soap:operation soapAction="" />
			<wsdl:input>
				<soap:body parts="parameters" use="literal" />
				<soap:header message="tns:PSBHeader" part="addr"
					use="literal" />
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" />
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="HelloIF">
		<wsdl:port binding="tns:HelloIFSoapBinding" name="HelloIF">
			<soap:address
				location="http://192.168.0.143:8010/helloHolder/HelloIF" />
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>