
package com.ibm.ws.jaxws.test.namespacemismatch.service;

import javax.jws.WebService;
import javax.xml.ws.BindingType;

import com.ibm.ws.jaxws.test.namespacemismatch.stub.Hello;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 *
 */
//wsdlLocation = "file:/Users/berksanates/libertyGit/open-liberty/dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/test-applications/namespaceMismatchTest/resources/WEB-INF/wsdl/HelloService.wsdl",
@WebService(portName = "HelloPort", serviceName = "HelloService", targetNamespace = "http://namespacemismatch.test.jaxws.ws.ibm.com/",
            endpointInterface = "com.ibm.ws.jaxws.test.namespacemismatch.stub.Hello")
@BindingType("http://schemas.xmlsoap.org/wsdl/soap/http")
public class HelloService_HelloPortImpl implements Hello {

    public HelloService_HelloPortImpl() {
    }

    /**
     *
     * @param arg0
     * @return
     *         returns java.lang.String
     */
    @Override
    public String sayHello(String arg0) {
        //replace with your impl here
        return arg0;
    }

}
