
package com.ibm.ws.jaxws.test.namespacemismatch.stub;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 *
 */
@WebService(name = "Hello", targetNamespace = "http://namespacemismatch.test.jaxws.ws.ibm.com/")
@XmlSeeAlso({
              ObjectFactory.class
})
public interface Hello {

    /**
     *
     * @param arg0
     * @return
     *         returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://namespacemismatch.test.jaxws.ws.ibm.com/", className = "com.ibm.ws.jaxws.test.namespacemismatch.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://namespacemismatch.test.jaxws.ws.ibm.com/",
                     className = "com.ibm.ws.jaxws.test.namespacemismatch.SayHelloResponse")
    public String sayHello(
                           @WebParam(name = "arg0", header = true, targetNamespace = "") String arg0);

}
