
package hello;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 *
 */
@WebService(name = "HelloIF", targetNamespace = "http://hello")
@XmlSeeAlso({
              hello.ObjectFactory.class,
              org.xmlsoap.schemas.ws._2004._08.addressing.ObjectFactory.class
})
public interface HelloIF {

    /**
     *
     * @param header
     * @param address1
     * @return
     *         returns hello.SayHelloHeader
     */
    @WebMethod
    @WebResult(name = "sayHelloHeader", targetNamespace = "http://hello", partName = "result")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public void sayHelloHeader(
                               @WebParam(name = "sayHelloHeader", targetNamespace = "http://hello", mode = WebParam.Mode.INOUT, partName = "parameters") Holder<Address> address1,
                               @WebParam(name = "Header", targetNamespace = "http://hello", header = true, mode = WebParam.Mode.INOUT,
                                         partName = "Header") javax.xml.ws.Holder<Header> header);

    /**
     *
     * @param address1
     * @param address2
     */
    @WebMethod
    @RequestWrapper(localName = "updateAddress", targetNamespace = "http://hello", className = "hello.UpdateAddress")
    @ResponseWrapper(localName = "updateAddress", targetNamespace = "http://hello", className = "hello.UpdateAddress")
    public void updateAddress(
                              @WebParam(name = "Address", targetNamespace = "", mode = WebParam.Mode.INOUT) Holder<Address> address1,
                              @WebParam(name = "Address2", targetNamespace = "", mode = WebParam.Mode.INOUT) Holder<Address> address2);

    /**
     *
     * @param word
     * @param addr
     * @return
     *         returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "http://hello", partName = "arg0")
    @RequestWrapper(localName = "isPalindrome", targetNamespace = "http://hello", className = "hello.IsPalindrome")
    @ResponseWrapper(localName = "isPalindromeResponse", targetNamespace = "http://hello", className = "hello.IsPalindromeResponse")
//    @Action(input = "http://192.168.0.143:8010/helloHolder/HelloIF/isPalindromeRequest", output = "http://192.168.0.143:8010/helloHolder/HelloIF/isPalindromeResponse")
//    @Action(input = "http://inv.aat.tools.dlg.nl/WordInvertor/isPalindromeRequest", output = "http://inv.aat.tools.dlg.nl/WordInvertor/isPalindromeResponse")
    public boolean isPalindrome(
                                @WebParam(name = "arg0", targetNamespace = "") String word,
                                @WebParam(name = "SSCAddressing", targetNamespace = "", header = true, mode = WebParam.Mode.INOUT,
                                          partName = "addr") Holder<PSBAddressingType> addr);

}
